name: RT-AK with plugin-stm32 CI

on: [push, pull_request]

jobs:
  win10_stm32:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: [master, main]
        fetch-depth: 0
        lfs: true
        
    - name: download
      run : |
        pip install wget scons
        scons -v
        cd RT-AK/test
        python download_file.py
        ls ../tmp
        
        # run ai_tools.py
        cd ../rt_ai_tools
        python aitools.py --project="../tmp/sdk-bsp-artpi" --model='./Models/keras_mnist.h5' --platform='stm32' --ext_tools="../tmp/windows" --clear
        echo "Run RT-AK Tools done."
    
        # compiler
        cd ../tmp/sdk-bsp-artpi
        scons -j 6
        echo "Compiler done."
